name: bloc_ext
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/JUkhan/bloc_ext

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ">=0.25.0 <3.0.0"
  bloc: ">=6.0.0 <10.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner:
  build_test:
  test_coverage:
  ajwah_bloc_test:
